version: '3.4'

services:
  epolsoft.webapi:
    image: ${DOCKER_REGISTRY-}epolsoftwebapi
    build:
      context: .
      dockerfile: EpolSoftWebAPI/Dockerfile
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
